rootProject.name = "mypall"
include(":common-domain")
project(":common-domain").projectDir = file("common/common-domain")
include(":common-persistence-adapter")
project(":common-persistence-adapter").projectDir = file("common/adapters/common-persistence-adapter")
include(":common-web-adapter")
project(":common-web-adapter").projectDir = file("common/adapters/common-web-adapter")
include(":user-domain-core")
project(":user-domain-core").projectDir = file("user/user-domain/user-domain-core")
include(":user-application-service")
project(":user-application-service").projectDir = file("user/user-domain/user-application-service")
include(":user-adapter-web")
project(":user-adapter-web").projectDir = file("user/user-adapter/user-adapter-web")
include(":wallet-adapter-web")
project(":wallet-adapter-web").projectDir = file("wallet/wallet-adapter/wallet-adapter-web")
include(":wallet-domain-core")
project(":wallet-domain-core").projectDir = file("wallet/wallet-domain/wallet-domain-core")
include(":wallet-application-service")
project(":wallet-application-service").projectDir = file("wallet/wallet-domain/wallet-application-service")
include(":container")
